### ISSUE TITLE
how is the performance

### ISSUE THREAD

**Issue by danmoseley** [ShuiRuTian/SwissTable#1]
Hi @ShuiRuTian (posting here because in your runtime fork, issues are disabled)

I work on dotnet/runtime. I'm curious whether you have gotten benchmark results of this vs the regular dictionary. Are there scenarios where it is significantly faster? Is the vectorization mainly helpful when there is significant load factor (ie many collisions)? Is it more storage efficient?

**Comment by ShuiRuTian** [comment]
Hi, pretty glad to be able to catch the attention from Runtime team.

And sorry there is no attached data, I forget the accurate number, maybe I could find it somewhere in my laptop.

> Is it more storage efficient?

Yes, as mentioned I have forgotten about the data, but it's smaller than the size of current C# implementation.

I think it should save at least about 40% space for reference type, because we do not need to store entries any more.

Sorry for I did not put too much attention about the memory at that time, because of performance.

> Are there scenarios where it is significantly faster? 
> Is the vectorization mainly helpful when there is significant load factor (ie many collisions)? 

Interesting though, less memory allocation does not lead to better performance in test cases. (Test cases are from https://github.com/dotnet/performance)

When the capacity is pretty large, this Swisstable implementation is indeed faster.

But for real life cases, when the capacity is small, like 100, methods in C# implementation is usually 2-3x faster.

The only exception is about the methods related to "get from hashtable", Swisstable usually only takes 0.7x time.

I am not sure whether I did something wrong, I have checked the generated asm to modify some code. Maybe I need some more investigation.

Now I am waiting for next version of C#, to see whether we could get better control of low level.
And I am also reading "pro .NET memory management", which is really a good book, to see whether there are some skills to help.

But work occupies most of my time in the past half year. Let me see whether I could make progress in this year's hackathon.

**Comment by ShuiRuTian** [comment]
How large is "pretty large"?

It's kind of subtle, and I also forget the data, but it is at least larger than 10,000.

Java also has one swisstable, and there is a [post](https://leventov.medium.com/smoothiemap-2-the-lowest-memory-hash-table-ever-6bebd06780a3) from the author.

> Note: Our implementation is better than Java's because Java only supports SIMD(explicitly) on JAVA 18, and java's SwissTable repo is not that new.

In the post, it needs the capacity to be about 200,000.

Is there any case we need that large size of hashmap?

**Comment by danmoseley** [comment]
Yes certainly dictionaries are used that are that large. If you published to NuGet I expect it would get used. But from what you described, perhaps not general purpose enough to put in the core libraries at this point.

Thanks for the information though. If you do take another look and gather updated numbers, I'd be interested.

Cc @dotnet/area-system-collections @eiriktsarpalis

**Comment by danmoseley** [comment]
cc @stephentoub
